# Generated by Django 3.2.12 on 2022-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_user_registration_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_registration',
            name='contact_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='logo',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
