# Generated by Django 3.2.12 on 2022-03-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20220317_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acntspayslip',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desic', to='base_app.designation'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendanceuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departmentbranch', to='base_app.branch_registration'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designationbranch', to='base_app.branch_registration'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departmentbranch', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracurricularuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internshipbranch', to='base_app.branch_registration'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='paymentlist',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpay', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectdepartment', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectdesignation', to='base_app.designation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tester',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projecttester', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassignuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassignproject', to='base_app.project'),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassign_tester', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='tl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassigntl', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualificationuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='reported_issue',
            name='reported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issuereported_to', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='reported_issue',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issuereporter', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskdepartment', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskdesignation', to='base_app.designation'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_statusproject', to='base_app.project'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_statustaskname', to='base_app.project_taskassign'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='taskname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_statustaskname', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_statususer', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statusproject', to='base_app.project'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statussubtask', to='base_app.project_taskassign'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statustask', to='base_app.project_taskassign'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statustester', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statususer', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='trainee',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topictrainee', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topictrainer', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='trainer_task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_task_trainee', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userregistrationbranch', to='base_app.branch_registration'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userregistrationdepartment', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userregistrationdesignation', to='base_app.designation'),
        ),
    ]
