# Generated by Django 3.2.12 on 2022-03-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20220317_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='enddate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='joiningdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='startdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
