# Generated by Django 3.2.12 on 2022-03-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20220317_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='account_no',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
    ]
