# Generated by Django 3.2.12 on 2022-03-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_auto_20220318_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='status',
            field=models.CharField(default='active', max_length=240, null=True),
        ),
    ]
