# Generated by Django 3.2.12 on 2022-03-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_user_registration_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch_registration',
            old_name='contact_number',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch', to='base_app.branch_registration'),
        ),
    ]
