# Generated by Django 3.2.12 on 2022-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_auto_20220318_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_status',
            old_name='files',
            new_name='json',
        ),
        migrations.AddField(
            model_name='test_status',
            name='json_testerscreenshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
