# Generated by Django 3.2.12 on 2022-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_auto_20220319_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_status',
            name='json',
        ),
        migrations.AlterField(
            model_name='test_status',
            name='json_testerscreenshot',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
