# Generated by Django 3.2.12 on 2022-03-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_auto_20220319_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_status',
            name='json',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='json_testerscreenshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
