# Generated by Django 3.2.12 on 2022-03-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_auto_20220319_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_taskassign',
            name='delay',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
