# Generated by Django 4.0 on 2022-04-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_project_taskassign_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promissory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inital_amount', models.IntegerField(blank=True, null=True)),
                ('inital_paid_on', models.DateField(blank=True, null=True)),
                ('inital_paid_amount', models.IntegerField(blank=True, null=True)),
                ('inital_paid_date', models.DateField(blank=True, null=True)),
                ('inital_balance_amount', models.IntegerField(blank=True, null=True)),
                ('inital_due_date', models.DateField(blank=True, null=True)),
                ('inital_total_payment', models.IntegerField(blank=True, null=True)),
                ('second_amount', models.IntegerField(blank=True, null=True)),
                ('second_paid_on', models.DateField(blank=True, null=True)),
                ('second_paid_amount', models.IntegerField(blank=True, null=True)),
                ('second_paid_date', models.DateField(blank=True, null=True)),
                ('second_balance_amount', models.IntegerField(blank=True, null=True)),
                ('second_due_date', models.DateField(blank=True, null=True)),
                ('second_total_payment', models.IntegerField(blank=True, null=True)),
                ('final_amount', models.IntegerField(blank=True, null=True)),
                ('final_paid_on', models.DateField(blank=True, null=True)),
                ('final_paid_amount', models.IntegerField(blank=True, null=True)),
                ('final_paid_date', models.DateField(blank=True, null=True)),
                ('final_balance_amount', models.IntegerField(blank=True, null=True)),
                ('final_due_date', models.DateField(blank=True, null=True)),
                ('final_total_payment', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promissory_user', to='base_app.user_registration')),
            ],
        ),
    ]
