# Generated by Django 4.0 on 2022-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_promissory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promissory',
            name='final_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_balance_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_due_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_paid_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_paid_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_paid_on',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_total_payment',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_balance_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_due_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_on',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_total_payment',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_balance_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_due_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_paid_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_paid_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_paid_on',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_total_payment',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
