# Generated by Django 4.0 on 2022-04-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_alter_promissory_final_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promissory',
            name='final_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_balance_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_paid_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_total_payment',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_balance_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_total_payment',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_balance_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_paid_amount',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_total_payment',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
