# Generated by Django 4.0 on 2022-04-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_rename_final_paid_on_promissory_final_due_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promissory',
            name='final_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='final_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='inital_paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='second_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
