# Generated by Django 4.0 on 2022-04-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_promissory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promissory',
        ),
    ]
