# Generated by Django 4.0 on 2022-04-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0021_promissory'),
    ]

    operations = [
        migrations.AddField(
            model_name='promissory',
            name='compleate_status',
            field=models.CharField(blank=True, default='0', max_length=1000, null=True),
        ),
    ]
