# Generated by Django 4.0 on 2022-04-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_promissory_compleate_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promissory',
            old_name='compleate_status',
            new_name='complete_status',
        ),
    ]
